jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - name: Install atspkg
        run: |
          curl -sSl https://raw.githubusercontent.com/vmchale/atspkg/master/bash/install.sh | sh -s
      - name: Build ATS
        run: |
          export PATH=$HOME/.local/bin:$PATH
          atspkg -V
          atspkg build -vv 
      - name: Test ATS
        run: |
          export PATH=$HOME/.local/bin:$PATH
          atspkg test -vv 
name: ATS CI
on:
  - push
